<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '% of answers "Yes"' => '% ответов "да"',
    '<strong>Error!</strong> The opinion was not sent! Repeat again after some time.' => '<strong>Ошибка!</strong> Этот отзыв не был добавлен! Повторите через некоторое время.',
    '<strong>Success!</strong> Feedback successfully sent to moderation.' => '<strong>Успешно!</strong> Отзыв успешно отправлен на модерацию!',
    '<strong>Success!</strong> Opinion deleted successfully.' => '<strong>Успешно!</strong> Отзыв успешно удален',
    '<strong>Success!</strong> Your review add.' => '<strong>Успешно!</strong> Ваш ответ успешно добавлен',
    'Add a review' => 'Добавить комментарий',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Create' => 'Создать',
    'Create Reviews' => 'Добавить отзыв',
    'Criterion' => 'Критерий',
    'Data' => 'Данные',
    'Date Create' => 'Дата Создания',
    'Date Update' => 'Дата Обновления',
    'Delete' => 'Удалить',
    'Delete review' => 'Удалить',
    'Edit review' => 'Редактировать',
    'Element cannot be blank.' => 'Элемент не может быть пустым',
    'Leave a review' => 'Оставить отзыв',
    'Level' => 'Уровень',
    'New reviews to {0}' => 'Новые отзывы к {0}',
    'Page' => 'Страницы',
    'Rating' => 'Рейтинг',
    'Reply' => 'Ответить',
    'Reset' => 'Сброс',
    'Reviews' => 'Отзывы',
    'Reviews Child' => 'Отзыв-ребенок',
    'Reviews ID' => 'Id отзыва',
    'Reviews Parent' => 'Отзыв-родитель',
    'Search' => 'Искать',
    'Status' => 'Статус',
    'Text' => 'Текст отзыва',
    'The "pageIdentifier" property must be set.' => 'Свойство "pageIdentifier" должно быть установлено',
    'The "statisticsReviews" property must be set.' => 'Свойство "statisticsReviews" должно быть установлено',
    'The number of responses' => 'Количество ответов',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => 'Обновление {modelClass}: ',
    'User ID' => 'Идентификатор пользователя',
    'View page' => 'Просмотр страницы',
    'says' => 'написал',
    'Send new review' => 'Добрый день. К вашему объявлению добавили новый отзыв.<br>',
    'Send new review for page {url}' => 'Чтобы посмотреть отзыв, оставить свой ответ на него перейдите на страницу объявления: {url}',
    'Send new response' => 'Новый ответ',
    'Was written the answer to your review on the page {url}' => 'Вам ответили на странице {url}',
    'Success review' => 'Одобрить'
];
